// src/components/partiicipantsData.js
export const partiicipants = [
  { company: "山田商事", name: "山田太郎", count: 2, status: "出席" },
  { company: "佐藤製作所", name: "佐藤花子", count: 1, status: "欠席" },
  { company: "田中工業", name: "田中一郎", count: 3, status: "出席" },
  { company: "鈴木印刷", name: "鈴木健一", count: 4, status: "出席" },
  { company: "高橋電機", name: "高橋由美", count: 1, status: "欠席" },
  { company: "伊藤建設", name: "伊藤誠", count: 2, status: "出席" },
  { company: "渡辺食品", name: "渡辺麻衣", count: 5, status: "出席" },
  { company: "中村産業", name: "中村翔太", count: 2, status: "欠席" },
  { company: "小林商会", name: "小林仁", count: 1, status: "出席" },
  { company: "加藤金属", name: "加藤陽子", count: 3, status: "出席" },
  { company: "吉田運輸", name: "吉田健", count: 2, status: "出席" },
  { company: "山本印刷", name: "山本愛", count: 3, status: "欠席" },
  { company: "井上化学", name: "井上翔", count: 2, status: "出席" },
  { company: "清水物流", name: "清水浩", count: 1, status: "出席" },
  { company: "森田商店", name: "森田優", count: 4, status: "欠席" },
  { company: "岡田金属", name: "岡田健太", count: 3, status: "出席" },
  { company: "村上工務店", name: "村上亮", count: 1, status: "出席" },
  { company: "長谷川企画", name: "長谷川詩織", count: 2, status: "出席" },
  { company: "原田建設", name: "原田悟", count: 3, status: "出席" },
  { company: "石井電機", name: "石井美咲", count: 2, status: "欠席" },
  { company: "藤田製作所", name: "藤田拓真", count: 4, status: "出席" },
  { company: "西村食品", name: "西村花", count: 2, status: "出席" },
  { company: "青木商事", name: "青木健", count: 5, status: "出席" },
  { company: "松井産業", name: "松井徹", count: 2, status: "欠席" },
  { company: "堀内運送", name: "堀内仁", count: 3, status: "出席" },
  { company: "竹内商会", name: "竹内真理", count: 2, status: "出席" },
  { company: "中川印刷", name: "中川亮", count: 3, status: "欠席" },
  { company: "柴田工業", name: "柴田誠", count: 2, status: "出席" },
  { company: "宮本設計", name: "宮本優子", count: 4, status: "出席" },
  { company: "黒田商店", name: "黒田翔", count: 1, status: "出席" },
];
